const imgsData = [
  { src: "img/angry-gamer-boy.jpg", matched: false },
  { src: "img/astronaut-dabbing.jpg", matched: false },
  { src: "img/astronaut-dance.jpg", matched: false },
  { src: "img/astronaut-out-laptop.jpg", matched: false },
  { src: "img/astronaut-riding-rocket.jpg", matched: false },
  { src: "img/astronaut-wearing-hoodie.jpg", matched: false },
  { src: "img/bad-cat.jpg", matched: false },
  { src: "img/boy-going-school.jpg", matched: false },
  { src: "img/boy-playing-computer.jpg", matched: false },
  { src: "img/boy-with-money-gun.jpg", matched: false },
  { src: "img/burger-skateboard.jpg", matched: false },
  { src: "img/cat-gamer.jpg", matched: false },
  { src: "img/corgi-dog-ramen.jpg", matched: false },
  { src: "img/dinasour.jpg", matched: false },
  { src: "img/hand-drawn.jpg", matched: false },
  { src: "img/hand-drawn-meat.jpg", matched: false },
  { src: "img/heart-angel-love.jpg", matched: false },
  { src: "img/koala-floating-balloon.jpg", matched: false },
  { src: "img/koala-with-cub.jpg", matched: false },
  { src: "img/monkey-holding-money.jpg", matched: false },
  { src: "img/monster-kid.jpg", matched: false },
  { src: "img/monster-kid-2.jpg", matched: false },
  { src: "img/mushroom-with-bowtie.jpg", matched: false },
  { src: "img/ninja-working.jpg", matched: false },
  { src: "img/panda-cartoon.jpg", matched: false },
  { src: "img/pencil-waving.jpg", matched: false },
  { src: "img/penguin-love.jpg", matched: false },
  { src: "img/pepa-pig.jpg", matched: false },
  { src: "img/phone.jpg", matched: false },
  { src: "img/pill-medicine-chef.jpg", matched: false },
  { src: "img/pose-doughtnut.jpg", matched: false },
  { src: "img/robot-holding-magnifying.jpg", matched: false },
  { src: "img/slice-pizza.jpg", matched: false },
  { src: "img/super-pencil.jpg", matched: false },
  { src: "img/vintage-tv-shock.jpg", matched: false },
];

export { imgsData };
